spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mitratech
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600
server:
  port: 9000

logging:
  level:
    root: info

management:
  endpoint:
    health:
      show-detail: always
      show-components: always
